### ISSUE TITLE
Deleting books will not remove them from hard drive

### ISSUE THREAD

**Issue by Tarow** [Readarr/Readarr#2224]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When deleting individual books from the web ui with the `delete the book files` option enabled, the files will be removed from the Readarr library, however they are not actually deleted on the filesystem. I tested this with multiple books from different authors (e. g. Armada from Ernest Cline) and the books were still present on the file system in every case.

When deleting an author including all its books, the author folder is actually deleted successful, so this issue only exists for individual books.

### Expected Behavior

When checking the `delete book files` option, the files should be deleted on the file system.

### Steps To Reproduce

1. Docker environment:
```
version: "3.7"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./readarr-config:/config
      - /mnt/hdd1/media:/media
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.readarr.rule=Host(`readarr.somedomain.com`)"
      - "traefik.http.routers.readarr.entrypoints=websecure"
      - "traefik.http.services.readarr.loadbalancer.server.port=8787"

networks:
  traefik-proxy:
    external: true
```

2. Download or import an book for any author
3. Try to delete the book from the UI with the `delete book files` checkmark set.
4. Check if the file was actually deleted from the file system

### Environment

```markdown
- OS: Arch (6.1.12 Kernel)
- Readarr: 0.1.3.1584
- Docker Install: Yes
- Using Reverse Proxy: Yes, Traefik
- Browser: Firefox 111.0b5
- Database: Sqlite 3.40.1
```

### What branch are you running?

Develop

### Trace Logs?

[Readarr.trace.txt](https://github.com/Readarr/Readarr/files/10832252/Readarr.trace.txt)

![img1](https://user-images.githubusercontent.com/15030658/221379507-e653c8a2-e154-4f54-9a66-79a54068088d.png)
