### ISSUE TITLE
Installing on Raspberry Pi 4 with Docker Compose isn't starting

### ISSUE THREAD

**Issue by starbuck93** [Readarr/Readarr#453]
**Describe the bug**
I cannot get Readarr to start on my Raspberry Pi 4. I added the following to my docker-compose.yml and the container does not appear to start:

`docker-compose.yml`

```yaml
version: '3.3'
services:
  readarr:  
    image: hotio/readarr:unstable  
    container_name: readarr  
    restart: unless-stopped  
    ports:  
      - 8787:8787  
    volumes:  
      - /mnt/usb/docker/readarr/config:/config  
      - /mnt/usb/docker/readarr/books:/books  
      - /mnt/usb/docker/readarr/audiobooks:/audiobooks  
      - /mnt/usb/docker/readarr/downloads:/data/downloads/Seeding/Books  
      - /etc/localtime:/etc/localtime:ro  
    environment:  
      - PUID=1000  
      - PGID=1000  
      - TZ=America/New_York
... 
```

**To Reproduce**
1. Add the above to `docker-compose.yml`
2. run `docker-compose up -d`
3. run `docker logs -f readarr`
4. Navigating to IP_ADDRESS:8787 (with Chrome, in my case) says `ERR_CONNECTION_REFUSED`

**Expected behavior**
I expected to see Readarr initializing

**Screenshots**

**Logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-start-container: executing...

----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=1000
PGID=1000
UMASK=002
TZ=America/New_York
ARGS=
DEBUG=no
----------------------------------------------------------------------

Executing usermod...
usermod: no changes
Applying permissions to /config
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**System info (please complete the following information):**
 - Readarr Version: Unsure. Maybe 0.1.0.247
 - Raspbian (Linux hostname 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux)
 - ~.net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]~
 - Docker version 19.03.12, build 48a6621
 - docker-compose version 1.24.1, build 4667896

**Additional context**
